KEY_WORD("pakul", 6, "while", WHILE, "loop_while", 0x001)
KEY_WORD("kali", 4, "if", IF, "if_condition", 0x002)
KEY_WORD("=", 1, "=", EQUALS, "assigning", 0x003)
KEY_WORD(">", 1, ">", OPERATION, "ja", 0x004)
KEY_WORD("<", 1, "<", OPERATION, "jb", 0x005)
KEY_WORD("+", 1, "+", OPERATION, "add", 0x006)
KEY_WORD("-", 1, "-", OPERATION, "sub", 0x007)
KEY_WORD(";", 1, ";", END_OF_STR, "endofoper", 0x008)
KEY_WORD("(", 1, "(", PARENTHESIS, "left_bracket", 0x009)
KEY_WORD(")", 1, ")", PARENTHESIS, "right_bracket", 0x00A)
KEY_WORD("pachac", 1, "{", PARENTHESIS, "left_figure_bracket", 0x00B)
KEY_WORD("skoncyc", 1, "}", PARENTHESIS, "right_figure_bracket", 0x00C)
KEY_WORD ("main", 4, "main", FUNCTION, "main", 0x00D)
KEY_WORD ("vyarnut", 6, "return", RETURN, "ret", 0x00E)
KEY_WORD ("nadrukavac", 10, "printf", FUNCTION, "out", 0x00F)
KEY_WORD ("atrymac", 7, "scanf", FUNCTION, "in", 0x010)
KEY_WORD("*", 1, "*", OPERATION, "mul", 0x011)
KEY_WORD("/", 1, "/", OPERATION, "div", 0x012)
KEY_WORD("==", 2, "==", OPERATION, "je", 0x013)